Feature/implement post creation
ashleywd/SIT725-T32024-Group-Project pull request #6
Opened 2024-12-11 15:10 UTC by s223561464

2024-12-12 03:26 UTC, ashleywd commented
hey @daosgava , I hope you dont mind me allocating this to you for review. I can also give to Marlon if you want to spread the load around.

Changes are:
- Created postController
- Updated post model to include a field for hours babysitting needed. Temporarily changed the userID to a string so we can do testing.
- Updated index.html with a modal which contains a basic form incl manual input for userID.
- Updated main.js for event listeners.
- Added routes for postController and changed references to the controller to appController
- Minor changes to server.js

2024-12-12 12:07 UTC, daosgava requested changes
It looks great. I really like how you document your code. I left a few comments that could benefit the project. I also have a question about the post model: As a user, do you need points to apply for a job, or can anyone apply? If points are required to apply, you'll need to define the number of required points in the post model. This would be separate from the number of points a user has.

2024-12-12 12:07 UTC, daosgava commented on public/js/main.js
> +document.addEventListener('DOMContentLoaded', function() {
If you use the defer argument you won't need this event listener.

2024-12-12 12:07 UTC, daosgava commented on public/js/main.js
> +});
I think we should also keep the JS code in separate files because it will get larger as we add more components. Additionally, this will help separate the logic, making it easier to maintain.

2024-12-12 12:07 UTC, daosgava commented on routes/app.js
> +router.get('/posts', postController.getAllPosts);
This routes are not part of the app. This should be moved to a post.js file.

2024-12-12 12:12 UTC, daosgava commented
It would also be great to add a description of what this change is about and link the Trello card.

2024-12-12 13:17 UTC, ashleywd commented
@daosgava to answer your question about the needing points to post, the points that would be required to post (which has not been implemented) = the number of hours on a 1:1 basis. So posting a request for babysitting for 1hr would take 1 point from the user profile (after the job is completed). We may not need to have a reference to posts specifically in the post. Let me know if my logic is wrong?

2024-12-12 13:28 UTC, s223561464 commented
I have a question which might not sound that relevant, but why do we need points? Why to make it so complex?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: ashleywd ***@***.***>
Sent: Friday, December 13, 2024 12:17:46 AM
To: ashleywd/SIT725-T32024-Group-Project ***@***.***>
Cc: SALONI MEHTA ***@***.***>; Author ***@***.***>
Subject: Re: [ashleywd/SIT725-T32024-Group-Project] Feature/implement post creation (PR #6)


@daosgava<https://github.com/daosgava> to answer your question about the needing points to post, the points that would be required to post (which has not been implemented) = the number of hours on a 1:1 basis. So posting a request for babysitting for 1hr would take 1 point from the user profile (after the job is completed). We may not need to have a reference to points specifically in the post. Let me know if my logic is wrong?

—
Reply to this email directly, view it on GitHub<https://github.com/ashleywd/SIT725-T32024-Group-Project/pull/6#issuecomment-2538890659>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BBFEVS7P5FEG2OXJ5BBQNHL2FGEHVAVCNFSM6AAAAABTNWSPS6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMZYHA4TANRVHE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-12-12 23:17 UTC, ashleywd commented
The overall product concept is that parents trade their time in exchange for other parents time. Else you'd end up with a bunch of freeloaders who use other people's babysitting time without offering anything in return. However, we have not defined it as a must have requirement for core functionality so if we have time we will add it later.

2024-12-12 23:18 UTC, ashleywd commented on public/index.html
>      <script src="/js/main.js"></script>
@s223561464 did you want to address this? I was planning on making this change sometime later but we can do it now.

2024-12-12 23:27 UTC, ashleywd commented on public/index.html
>      <main class="container">
Are you thinking of using EJS @daosgava ? Do you think we can make this another Trello card and add it to our backlog? Or you think it should be done now?

2024-12-12 23:30 UTC, ashleywd commented on public/js/main.js
> +document.addEventListener('DOMContentLoaded', function() {
@s223561464 I suggest doing this while you implement the defer method

2024-12-12 23:30 UTC, ashleywd commented on public/js/main.js
> +});
@s223561464 you can do this too? Split up main.js into functionalities.

2024-12-12 23:31 UTC, ashleywd commented on routes/app.js
> +router.get('/posts', postController.getAllPosts);
@s223561464 you can implement this too if you want?

2024-12-13 03:20 UTC, daosgava commented on public/index.html
>      <main class="container">
Yeah, I have done it in the authentication PR.

2024-12-13 03:26 UTC, daosgava commented
@s223561464 @ashleywd Guys, I created the authentication PR where I am handling some of the things I mentioned. Regarding the points system, I think I got it. The number of points required to post is equal to the number of hours, and when a job is finished, the user will receive the equivalent number of points for the hours worked. That makes sense :).

2024-12-13 04:33 UTC, ashleywd commented
Merging our changes into main as discussed. Daniel will integrate our changes into his PR.

2024-12-13 04:33 UTC, merged