Feature/add account mgt
ashleywd/SIT725-T32024-Group-Project pull request #9
Opened 2024-12-20 04:42 UTC by marlon-deakin

Added the Account Management Feature

This pull request introduces the following functionalities for account management:

1. Account Details:
Display the account details of the currently logged-in user.

2 Edit/Update User Details:
Users can edit and update their account details.

3. Account Deletion:
 Users can delete their accounts.
 
4. Points Display:
The number of points is displayed on the navigation bar when the user is on the dashboard page.
Points cannot be edited by the user.

2024-12-20 04:48 UTC, ashleywd commented
Hey @marlon-deakin , I will pass to Daniel to review :). Will need to also resolve some conflicts.

2024-12-20 08:17 UTC, daosgava requested changes
@marlon-deakin You've made really good progress, but I think there are a few things we need to address. Let me help you with the changes. By the way, there are files from your machine that should not be pushed into this PR.

2024-12-20 08:17 UTC, daosgava commented on controllers/accountController.js
> +        }
I don't think we can have a scenario where a user requests an update, deletion, or information and does not exist in the database.

2024-12-20 08:17 UTC, daosgava commented on controllers/accountController.js
> +        }
Same here.

2024-12-20 08:17 UTC, daosgava commented on public/js/account.js
> +        document.getElementById('accountPoints').innerText = data.points || 0;
It's not possible for a user to log in without having this information.

2024-12-20 08:17 UTC, daosgava commented on public/js/account.js
> +        document.getElementById('pointsBadge').innerText = data.points || 0;
The points should only reflect the value from the database.

2024-12-21 04:52 UTC, marlon-deakin commented on controllers/accountController.js
> +        }
Probably for edge case scenarios such as the user being deleted while being logged in. Hower, I think that particular scenario doesn't apply to our app because only the user can delete their accounts themselves.

2024-12-21 07:48 UTC, marlon-deakin commented on controllers/accountController.js
> +        if (email) updateFields.email = email;
I have removed the conditionals in 46 and 47 , however I left the validation in line 40.
 // Validate required fields
        if (!username && !email) {
            return res.status(400).json({ error: 'At least one field (name or email) must be provided for update' });
        }
 My thought is that if there is a bug on the F/E validation then the above logic will avoid the creation of records with empty string.

2024-12-21 07:49 UTC, marlon-deakin commented on controllers/accountController.js
> +        }
Added the validation when the user edit/update the required fields in the front end.  However, i left the check in the controller. My thought is that if there is a bug on the F/E validation then the above logic will avoid the creation of records with empty string.

2024-12-21 08:00 UTC, marlon-deakin commented on views/partials/navbar.ejs
> +            <li><a id="pointsBadge" class="new badge"></a></li>
Thanks for pointing this out. Is pointsBadge  only relevant for the Account section or Dashboard.?
Let me know or confirm and I’ll update the navbar to conditionally render it or move it to the appropriate view template.

2024-12-23 03:00 UTC, daosgava reviewed
@marlon-deakin Thanks for making the updates. I slightly modified the frontend to use the Materialize components. However, I noticed that we are allowing users to edit fields that are unique in the database. This could be a problem. Let me know what you think, should we allow users to edit these fields?

2024-12-23 08:19 UTC, daosgava commented
@marlon-deakin I merged the main branch into your branch and addressed my comments. This PR is ready to be merged.

2024-12-23 08:20 UTC, daosgava approved these changes

2024-12-23 08:20 UTC, merged